config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :addresses
    resources :appointments
    resources :invoices
    resources :line_items
    root to: "users#index"
  end

  resources :appointments, only: [:index, :show]
  resources :invoices do
    resources :line_items
    get 'populate_address_list', to: 'invoices#populate_address_list', on: :collection
  end
  resources :addresses do
    get 'result', on: :member, to: 'addresses#show_verification_result'
  end
  get 'visitors/index'
  root to: 'visitors#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  before_create :set_ulid
  belongs_to :user
  belongs_to :address
  has_secure_token

  has_many :line_items, as: :itemable
  accepts_nested_attributes_for :line_items, allow_destroy: true, reject_if: :all_blank

  validates :identifier, :send_date, :due_date, presence: true

  def update_ulid
    set_ulid
    save
  end

  private

  def set_ulid
    self.unique_code = loop do
      ulid = ULID.generate
      break ulid unless Invoice.exists?(unique_code: ulid)
    end
  end
end

app/controllers/admin/invoices_controller.rb
module Admin
  class InvoicesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Invoice.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Invoice.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = current_user.invoices
    authorize @invoices
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = current_user.invoices.new
    authorize @invoice
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = invoices.new(invoice_params)
    authorize @invoice

    respond_to do |format|
      if @invoice.save!
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def populate_address_list
    user_id = params[:user_id]
    user = User.find(user_id)
    @addresses = user.addresses
    authorize @addresses
    respond_to do |format|
      format.json { render json: @addresses }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
      authorize @invoice
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:user_id, :address_id, :identifier, :token, :description, :send_date, :due_date,
                                     line_items_attributes: [:id, :title, :quantity, :unit_of_measure, :unit_price, :_destroy])
    end

    def not_authorized
      redirect_to invoices_url, alert: 'Sorry, you cannot do that.'
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.slim
= simple_form_for(@invoice) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.association :address
    = f.input :identifier
    = f.input :description
    = f.input :send_date
    = f.input :due_date
  - if @invoice.persisted?
    h2 First Line Items
    - @invoice.line_items.build unless @invoice.line_items.any?
    table.ui.table
      thead
        tr
          th Title
          th Unit Price
          th Quantity
          th Unit of Measure
          th Delete
      tbody
        = f.simple_fields_for :line_items do |li|
          tr
            td = li.input :title, label: false
            td = li.input :unit_price, as: :decimal, label: false
            td = li.input :quantity, label: false
            td = li.input :unit_of_measure, label: false
            td = li.input :_destroy, label: false, as: :radio_buttons

  .form-actions
    = f.button :submit
//- content_for(:javascript) do
  coffee:
    $(document).ready ->
      $("#invoice_user_id").on 'change', ->
        $.ajax
          url: "#{populate_address_list_invoices_path(@invoice)}"
          type: 'GET'
          data: user_id: $(this).val()
          success: (data) ->
            $('#invoice_address_id').children().remove()
            return
        return
      return
- content_for(:javascript) do
  javascript:
    $(document).ready(function() {
      $("#invoice_user_id").on('change', function() {
        $.ajax({
          url:"#{populate_address_list_invoices_path}.json",
          type:"GET",
          data:{user_id: $(this).val()},
          success: function(data) {
          console.log(data);
            $("#invoice_address_id").children().remove();
            data.forEach(function(item) {
              console.log(item);
              $("#invoice_address_id").append(
                "<option value=\""+ item.id +"\">" +item['nickname'] + "</option>"
              );
            })

          }
        })
      })
    });


// javascript:
  $(document).ready(function() {
    $('#invoice_user_id').on('change', function() {
      $ajax({
        url: "#{populate_address_list_invoices_path}",
        type: "GET",
        data: {user_id: $(this).val()},
        success: function(data) {
          $("#invoice_address_id").children().remove();
        }
        // Callbacks that will be explained
      });
    });
  });

app/views/invoices/_line_item_form.html.slim
= simple_form_for @invoice.line_items.new, 
  url: invoice_line_items_path(@invoice),
  remote: false do |f|

  = f.input :title
  = f.input :quantity
  = f.input :unit_of_measure
  = f.input :unit_price
  = f.submit

app/views/invoices/edit.html.slim
h1 Editing invoice

== render 'form'

= link_to 'Show', @invoice
'  |
= link_to 'Back', invoices_path

app/views/invoices/index.html.slim
h1 Listing invoices

table.ui.celled.table
  thead
    tr
      th User
      th Address
      th Send date
      th Due date
      th

  tbody
    - @invoices.each do |invoice|
      tr
        td = invoice.user
        td = invoice.address
        td = invoice.send_date
        td = invoice.due_date
        td = link_to 'Show', invoice

br

app/views/invoices/new.html.slim
h1 New invoice

== render 'form'

= link_to 'Back', invoices_path

app/views/invoices/show.html.slim
h1 View Invoice &mdash; (<small>#{@invoice.unique_code}</small>)
table.ui.definition.table
  tbody
    tr
      td Address
      td = @invoice.address
    tr
      td Description
      td = @invoice.description
    tr
      td Send date
      td = @invoice.send_date
    tr
      td Due date
      td = @invoice.due_date
    - if current_user.admin?
      tr
        td Address Verification Result
        td = link_to 'View', result_address_path(@invoice.address)

h2 Line Items
table.ui.table.celled.line_items_table
  thead
    tr
      th Item
      th Qty.
      th UOM
      th Unit Price
      th Line Price
  tbody
    - @invoice.line_items.each do |item|
      tr
        td = item.title
        td = item.quantity
        td = item.unit_of_measure
        td = item.unit_price.format
        td = (item.unit_price * (item.quantity ? item.quantity : 0)).try(:format)
    tr
      td[colspan="3"]
      th Total
      td = @invoice.line_items.map{|item| (item.unit_price * (item.quantity ? item.quantity : 0))}.sum.try(:format)
hr
- if current_user.admin?
  h2 Add Line Item
  = render 'line_item_form'

= link_to 'Back', invoices_path