config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :addresses
    resources :appointments
    resources :invoices
    resources :line_items
    root to: "users#index"
  end

  resources :appointments, only: [:index, :show]
  resources :invoices do
    resources :line_items
    get 'populate_address_list', to: 'invoices#populate_address_list', on: :collection
  end
  resources :addresses do
    get 'result', on: :member, to: 'addresses#show_verification_result'
  end
  get 'visitors/index'
  root to: 'visitors#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = current_user.addresses
    authorize @addresses
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = current_user.addresses.new
    authorize @address
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = current_user.addresses.new(address_params)
    authorize @address

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_verification_result
    @address = Address.find(params[:id])
    authorize @address
    @result = @address.verification_result
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
      authorize @address
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:user_id, :nickname, :line1, :line2, :city, :state, :zip)
    end

    def not_authorized
      redirect_to root_path, notice: "Sorry, you are not allowed to do that."
    end
end

app/controllers/admin/addresses_controller.rb
module Admin
  class AddressesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Address.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Address.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.slim
= simple_form_for(@address) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nickname
    = f.input :line1
    = f.input :line2
    = f.input :city
    = f.input :state
    = f.input :zip
    = f.input :phone_number

  .form-actions
    = f.button :submit

app/views/addresses/edit.html.slim
h1 Editing address

== render 'form'

= link_to 'Show', @address
'  |
= link_to 'Back', addresses_path

app/views/addresses/index.html.slim
h1 Listing addresses

table.ui.celled.table
  thead
    tr
      th Nickname
      th City
      th State
      th

  tbody
    - @addresses.each do |address|
      tr
        td = address.nickname
        td = address.city
        td = address.state
        td = link_to 'Show', address

br

= link_to 'New Address', new_address_path

app/views/addresses/new.html.slim
h1 New address

== render 'form'

= link_to 'Back', addresses_path

app/views/addresses/show.html.slim
.content
  .header = @address.nickname
  .meta 
    span.category = @address.token
  .ui.divider
  table.ui.table.very.basic.collapsing
    tr
      th User
      td = @address.user.email
    tr
      th Verified Address
      td = simple_format @address.validated_address

= link_to 'Back', addresses_path

app/views/addresses/show_verification_result.html.slim
pre = raw(ap @result)