config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :addresses
    resources :appointments
    resources :invoices
    resources :line_items
    root to: "users#index"
  end

  resources :appointments, only: [:index, :show]
  resources :invoices do
    resources :line_items
    get 'populate_address_list', to: 'invoices#populate_address_list', on: :collection
  end
  resources :addresses do
    get 'result', on: :member, to: 'addresses#show_verification_result'
  end
  get 'visitors/index'
  root to: 'visitors#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  has_secure_token
end

app/controllers/admin/appointments_controller.rb
module Admin
  class AppointmentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Appointment.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Appointment.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointment, only: :show
  before_action :check_invalid_user, only: :show

  def index
    @appointments = current_user.appointments
  end

  def show
    

  end

  private

  def set_appointment
    @appointment = Appointment.find_by(token: params[:id])
  end

  def check_invalid_user
    redirect_to appointments_path unless ((current_user == @appointment.user) || current_user.admin?)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.slim
h1 Your Upcoming Appointments
.ui.message.blue <strong>Below is a list of your past and upcoming
  appointments.</strong> Please let me know if you need to cancel.
= month_calendar attribute: :starts_at, events: @appointments do |date, appts|
  em = date.strftime("%b %d")
  ul
    - appts.each do |appt|
      li
        - if appt.canceled?
          | <strike>
        |[#{appt.starts_at.strftime("%l:%M %p").strip}] #{link_to appt.description, appointment_path(appt.token)}
        - if appt.canceled?
          | </strike>
.ui.message.yellow All timezones are <em>America/Phoenix</em> (UTC -07:00).

app/views/appointments/show.html.slim
h1 Appointment Detail
table.ui.table.definition
  tbody
    tr
      td Description
      td = @appointment.description
    tr
      td Date / Time
      td = @appointment.starts_at.strftime('%b %d, %Y %I:%M %p')
    tr
      td Duration
      td 
        |#{@appointment.duration} minutes 
= link_to 'Go Back', appointments_path, class: 'ui button'